# Generated by Django 2.2.5 on 2019-09-26 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0003_auto_20190926_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='WalletMoney',
        ),
    ]
