# Generated by Django 2.2.6 on 2019-10-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0006_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authen',
            field=models.IntegerField(default=True),
        ),
    ]
