# Generated by Django 2.2.5 on 2019-10-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0008_auto_20191016_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=False, max_length=254, unique=True),
        ),
    ]
