# Generated by Django 2.2.5 on 2019-10-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0010_auto_20191016_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=models.CharField(max_length=255, unique=True), max_length=254),
        ),
    ]
