# Generated by Django 2.2.6 on 2019-10-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0012_friendship_friendshiprequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
