# Generated by Django 2.2.6 on 2019-10-18 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0014_friendship'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=2500)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('from_m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_m1', to=settings.AUTH_USER_MODEL)),
                ('to_m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_m2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
