# Generated by Django 2.2.6 on 2019-10-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0015_messagebox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(),
        ),
    ]
