# Generated by Django 2.2.6 on 2019-10-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0018_auto_20191018_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authenticated',
            field=models.IntegerField(default=0),
        ),
    ]
