# Generated by Django 2.2.6 on 2019-10-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0019_auto_20191018_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privacy',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='authenticated',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=1000),
        ),
    ]
