# Generated by Django 2.2.6 on 2019-10-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0021_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
