# Generated by Django 2.2.6 on 2019-10-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0023_auto_20191018_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timeline',
            field=models.BooleanField(default=True),
        ),
    ]
