# Generated by Django 2.2.6 on 2019-10-21 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0025_timeline_self'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeline',
            old_name='self',
            new_name='selfp',
        ),
    ]
