# Generated by Django 2.2.6 on 2019-10-24 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0026_auto_20191021_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('amtsent', models.IntegerField()),
                ('selfp', models.BooleanField(default=True)),
                ('balance', models.IntegerField()),
                ('from_t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from1', to=settings.AUTH_USER_MODEL)),
                ('to_t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
