# Generated by Django 2.2.6 on 2019-10-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0027_accountsummary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsummary',
            old_name='balance',
            new_name='balance1',
        ),
        migrations.AddField(
            model_name='accountsummary',
            name='balance2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
