# Generated by Django 2.2.6 on 2019-10-24 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0028_auto_20191024_0714'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountSummary',
        ),
    ]
