# Generated by Django 2.2.6 on 2019-10-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0031_pagecontent_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsummary',
            name='month',
            field=models.CharField(default='', max_length=50),
        ),
    ]
