# Generated by Django 2.2.6 on 2019-10-29 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0032_accountsummary_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsummary',
            old_name='month',
            new_name='mn',
        ),
    ]
