# Generated by Django 2.2.6 on 2019-10-29 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0033_auto_20191029_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsummary',
            name='mn',
        ),
    ]
