# Generated by Django 2.2.6 on 2019-10-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0035_groups_group_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
