# Generated by Django 2.2.5 on 2019-11-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0037_auto_20191030_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grpadm',
            field=models.BooleanField(default=False),
        ),
    ]
